name: Dependabot PR Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Notify team about Dependabot PR
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'New Dependabot PR opened: ${{ github.event.pull_request.html_url }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
